version: '3.1'

services:
  api:
    image: "abralic98/advanced-websockets"
    depends_on:
      - postgres
    ports:
        - "4000:4000"
   
  postgres:
    environment:
      - POSTGRES_DB=community_dev
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
        - "5432:5432"
    image: postgres:14
    volumes:
      - ./pgdata:/var/lib/postgresql/data
